### PR TITLE
Fix module

### LINKED ISSUE #70: Module migration did not encode major version
Release v2.1.1 cannot be used because the module migration was done incorrectly. Starting at v2, the module path must end in the major version.

See https://github.com/golang/go/wiki/Modules#semantic-import-versioning.

### PR DESCRIPTION
**Pull request by unguiculus**
Starting at v2, the module path must end in the major version.

The fakes were updated manually, which is not ideal. They seem
to have been edited manually before. I had tried to regenerate
but the tests wouldn't run.

Fixes #70

### CODE REVIEW

File: health.go [hunk 1]
```diff
@@ -2,7 +2,7 @@
 //
 // For additional overview, documentation and contribution guidelines, refer to the project's "README.md".
 //
-// For example usage, refer to https://github.com/InVisionApp/go-health/tree/master/examples/simple-http-server.
+// For example usage, refer to https://module github.com/InVisionApp/go-health/v2/tree/master/examples/simple-http-server.
```
Comment (hebime) [inline health.go]: Typo here?

**Comment by hebime** [comment]
Thanks for the fix! We'll get this in ASAP!

File: health.go (hunk 1 above)
Comment (unguiculus) [reply health.go]: Fixed. Thanks.

**Comment by leonenkoa** [comment]
Hey, why this PR is still open ? Can you please merge it ?
